import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { nextLanguage, normalizeLanguagePreference } from '@/lib/language';

export type Language = 'en' | 'hi';
const copy = {
  en: {
    'nav.home': 'Home', 'nav.explore': 'Explore', 'nav.states': 'States', 'nav.traditions': 'Folk Traditions', 'nav.about': 'About', 'nav.upload': 'Upload Folk Music',
    'search.label': 'Search folk music', 'search.placeholder': 'Search songs, artists, states, languages or traditions', 'search.none': 'No matching songs, places or traditions found.', 'search.results': 'Search results',
    'hero.eyebrow': 'From the people · to the world', 'hero.archive': 'A Living Folk Music Archive', 'hero.line1': 'Give every fading tune', 'hero.line2': 'a new identity', 'hero.support': 'Preserve the songs of our roots. Carry their voices to the world.', 'hero.body': 'LokTaal is a living platform where artists and communities can share, preserve and introduce folk music to new listeners.', 'hero.explore': 'Explore Folk Music', 'hero.upload': 'Upload a Folk Song', 'hero.credit': 'Artist-first credits', 'hero.regional': 'Regional discovery', 'hero.preservation': 'Community preservation',
    'states.eyebrow': 'Explore India', 'states.title': 'Every state carries a different rhythm', 'states.body': 'Browse all 28 states and 8 Union Territories. Collections grow only when properly credited recordings are contributed.', 'states.search': 'Search a state or Union Territory', 'states.state': 'State', 'states.ut': 'Union Territory', 'states.coming': 'Recordings coming soon',
    'auth.login': 'Log in to LokTaal', 'auth.signup': 'Create your LokTaal account', 'auth.email': 'Email address', 'auth.password': 'Password', 'auth.fullName': 'Full name', 'auth.confirm': 'Confirm password', 'auth.show': 'Show password', 'auth.hide': 'Hide password', 'auth.forgot': 'Forgot password?', 'auth.noAccount': 'New to LokTaal?', 'auth.haveAccount': 'Already have an account?', 'auth.preview': 'Continue with authenticated UI preview', 'auth.previewNote': 'Frontend preview only — no account or password is stored.', 'auth.backendPending': 'Authentication will activate after Supabase is connected.', 'auth.terms': 'I agree to the Terms and Privacy Policy.',
    'upload.title': 'Preserve a folk song', 'upload.intro': 'Prepare the recording, context and permission details for review.', 'upload.contributor': 'Contributor details', 'upload.song': 'Song details', 'upload.files': 'Files and preview', 'upload.rights': 'Rights and consent', 'upload.submit': 'Validate submission', 'upload.pending': 'Your submission is ready. Connect Supabase to securely upload and publish this song.', 'upload.review': 'I understand this submission will be reviewed before publication.', 'upload.consent': 'I confirm that I own this recording or have permission to upload and publish it on LokTaal.', 'upload.contributorName': 'Contributor / full name', 'upload.relationship': 'Relationship to the recording', 'upload.songTitle': 'Song title', 'upload.artist': 'Artist / performer name', 'upload.state': 'State or Union Territory', 'upload.district': 'District / region', 'upload.language': 'Language / dialect', 'upload.tradition': 'Folk genre / tradition', 'upload.instruments': 'Instruments used', 'upload.year': 'Year recorded (optional)', 'upload.description': 'Short description', 'upload.context': 'Cultural story / context', 'upload.lyrics': 'Lyrics (optional)', 'upload.tags': 'Tags (comma separated)', 'upload.audio': 'MP3 or M4A audio', 'upload.cover': 'JPG, PNG or WebP cover', 'upload.noUpload': 'No file will be uploaded yet.',
    'common.required': 'This field is required.', 'common.backHome': 'Back to homepage', 'common.remove': 'Remove', 'common.replace': 'Replace', 'common.loading': 'Preparing the LokTaal archive…',
    'notFound.title': 'Page not found', 'notFound.body': 'The page you are looking for may have moved, or the address may be incorrect.', 'notFound.home': 'Return Home',
    'global.eyebrow': 'Global Folk Traditions', 'global.title': 'Folk traditions beyond India', 'global.body': 'An upcoming expansion for carefully credited traditions from communities around the world.', 'global.upcoming': 'Upcoming expansion',
    'demo.room': 'Demo listening room', 'demo.title': 'Six synthetic tunes for player testing', 'demo.body': 'Every clip is clearly labelled demo audio and is not represented as an authentic regional recording.',
    'audio.play': 'Play', 'audio.pause': 'Pause', 'audio.paused': 'Paused', 'audio.playDemo': 'Play demo', 'audio.demoLabel': 'Synthetic demo audio', 'audio.volume': 'Volume', 'audio.mute': 'Mute', 'audio.unmute': 'Unmute', 'audio.progress': 'Playback progress', 'audio.loading': 'Loading preview…', 'audio.error': 'This preview could not be played.', 'audio.previewUnavailable': 'Preview unavailable', 'audio.close': 'Close player', 'audio.nowPlaying': 'Now playing',
  },
  hi: {
    'nav.home': 'मुखपृष्ठ', 'nav.explore': 'खोजें', 'nav.states': 'राज्य', 'nav.traditions': 'लोक परंपराएँ', 'nav.about': 'हमारे बारे में', 'nav.upload': 'लोक संगीत अपलोड करें',
    'search.label': 'लोक संगीत खोजें', 'search.placeholder': 'गीत, कलाकार, राज्य, भाषा या परंपरा खोजें', 'search.none': 'कोई मेल खाता गीत, स्थान या परंपरा नहीं मिली।', 'search.results': 'खोज परिणाम',
    'hero.eyebrow': 'लोक से · दुनिया तक', 'hero.archive': 'एक जीवंत लोक संगीत संग्रह', 'hero.line1': 'हर मिटती धुन को', 'hero.line2': 'मिले नई पहचान', 'hero.support': 'अपनी जड़ों के गीतों को सुरक्षित रखें। उनकी आवाज़ दुनिया तक पहुँचाएँ।', 'hero.body': 'लोकताल एक जीवंत मंच है जहाँ कलाकार और समुदाय लोकधुनें साझा और सुरक्षित कर सकते हैं तथा नए श्रोताओं तक पहुँचा सकते हैं।', 'hero.explore': 'लोक संगीत खोजें', 'hero.upload': 'लोकधुन अपलोड करें', 'hero.credit': 'कलाकार को पहला श्रेय', 'hero.regional': 'क्षेत्रीय खोज', 'hero.preservation': 'समुदाय द्वारा संरक्षण',
    'states.eyebrow': 'भारत की खोज', 'states.title': 'हर राज्य की अपनी अलग लय है', 'states.body': 'सभी 28 राज्यों और 8 केंद्र शासित प्रदेशों को देखें। संग्रह केवल उचित श्रेय वाली रिकॉर्डिंग से बढ़ता है।', 'states.search': 'राज्य या केंद्र शासित प्रदेश खोजें', 'states.state': 'राज्य', 'states.ut': 'केंद्र शासित प्रदेश', 'states.coming': 'रिकॉर्डिंग जल्द आएँगी',
    'auth.login': 'लोकताल में लॉग इन करें', 'auth.signup': 'लोकताल खाता बनाएँ', 'auth.email': 'ईमेल पता', 'auth.password': 'पासवर्ड', 'auth.fullName': 'पूरा नाम', 'auth.confirm': 'पासवर्ड की पुष्टि करें', 'auth.show': 'पासवर्ड दिखाएँ', 'auth.hide': 'पासवर्ड छिपाएँ', 'auth.forgot': 'पासवर्ड भूल गए?', 'auth.noAccount': 'लोकताल पर नए हैं?', 'auth.haveAccount': 'पहले से खाता है?', 'auth.preview': 'प्रमाणित UI पूर्वावलोकन जारी रखें', 'auth.previewNote': 'केवल फ्रंटएंड पूर्वावलोकन — कोई खाता या पासवर्ड सहेजा नहीं जाता।', 'auth.backendPending': 'Supabase जुड़ने के बाद प्रमाणीकरण सक्रिय होगा।', 'auth.terms': 'मैं नियमों और गोपनीयता नीति से सहमत हूँ।',
    'upload.title': 'एक लोकधुन सुरक्षित करें', 'upload.intro': 'समीक्षा के लिए रिकॉर्डिंग, संदर्भ और अनुमति का विवरण तैयार करें।', 'upload.contributor': 'योगदानकर्ता का विवरण', 'upload.song': 'गीत का विवरण', 'upload.files': 'फ़ाइलें और पूर्वावलोकन', 'upload.rights': 'अधिकार और सहमति', 'upload.submit': 'सबमिशन जाँचें', 'upload.pending': 'आपका सबमिशन तैयार है। इस गीत को सुरक्षित रूप से अपलोड और प्रकाशित करने के लिए Supabase जोड़ें।', 'upload.review': 'मैं समझता/समझती हूँ कि प्रकाशन से पहले इस सबमिशन की समीक्षा होगी।', 'upload.consent': 'मैं पुष्टि करता/करती हूँ कि यह रिकॉर्डिंग मेरी है या इसे लोकताल पर अपलोड और प्रकाशित करने की अनुमति मेरे पास है।', 'upload.contributorName': 'योगदानकर्ता / पूरा नाम', 'upload.relationship': 'रिकॉर्डिंग से संबंध', 'upload.songTitle': 'गीत का शीर्षक', 'upload.artist': 'कलाकार / प्रस्तोता का नाम', 'upload.state': 'राज्य या केंद्र शासित प्रदेश', 'upload.district': 'ज़िला / क्षेत्र', 'upload.language': 'भाषा / बोली', 'upload.tradition': 'लोक शैली / परंपरा', 'upload.instruments': 'प्रयुक्त वाद्य', 'upload.year': 'रिकॉर्डिंग का वर्ष (वैकल्पिक)', 'upload.description': 'संक्षिप्त विवरण', 'upload.context': 'सांस्कृतिक कथा / संदर्भ', 'upload.lyrics': 'बोल (वैकल्पिक)', 'upload.tags': 'टैग (कॉमा से अलग)', 'upload.audio': 'MP3 या M4A ऑडियो', 'upload.cover': 'JPG, PNG या WebP कवर', 'upload.noUpload': 'अभी कोई फ़ाइल अपलोड नहीं होगी।',
    'common.required': 'यह जानकारी आवश्यक है।', 'common.backHome': 'मुखपृष्ठ पर वापस जाएँ', 'common.remove': 'हटाएँ', 'common.replace': 'बदलें', 'common.loading': 'लोकताल संग्रह तैयार हो रहा है…',
    'notFound.title': 'पृष्ठ नहीं मिला', 'notFound.body': 'जिस पृष्ठ को आप खोज रहे हैं वह स्थानांतरित हो सकता है या पता गलत हो सकता है।', 'notFound.home': 'मुखपृष्ठ पर लौटें',
    'global.eyebrow': 'वैश्विक लोक परंपराएँ', 'global.title': 'भारत से परे लोक परंपराएँ', 'global.body': 'दुनिया भर के समुदायों की उचित श्रेय वाली परंपराओं के लिए आगामी विस्तार।', 'global.upcoming': 'आगामी विस्तार',
    'demo.room': 'डेमो सुनने का कक्ष', 'demo.title': 'प्लेयर जाँच के लिए छह सिंथेटिक धुनें', 'demo.body': 'हर क्लिप को स्पष्ट रूप से डेमो ऑडियो बताया गया है; यह प्रामाणिक क्षेत्रीय रिकॉर्डिंग नहीं है।',
    'audio.play': 'चलाएँ', 'audio.pause': 'रोकें', 'audio.paused': 'रुका हुआ', 'audio.playDemo': 'डेमो चलाएँ', 'audio.demoLabel': 'सिंथेटिक डेमो ऑडियो', 'audio.volume': 'आवाज़', 'audio.mute': 'म्यूट करें', 'audio.unmute': 'आवाज़ चालू करें', 'audio.progress': 'प्लेबैक प्रगति', 'audio.loading': 'पूर्वावलोकन लोड हो रहा है…', 'audio.error': 'यह पूर्वावलोकन चलाया नहीं जा सका।', 'audio.previewUnavailable': 'पूर्वावलोकन उपलब्ध नहीं', 'audio.close': 'प्लेयर बंद करें', 'audio.nowPlaying': 'अभी चल रहा है',
  },
} as const;

type TranslationKey = keyof typeof copy.en;
interface I18nValue { language: Language; setLanguage: (language: Language) => void; toggleLanguage: () => void; t: (key: TranslationKey) => string; }
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => normalizeLanguagePreference(localStorage.getItem('loktaal-language')));
  const setLanguage = useCallback((next: Language) => { setLanguageState(next); localStorage.setItem('loktaal-language', next); }, []);
  const toggleLanguage = useCallback(() => setLanguage(nextLanguage(language)), [language, setLanguage]);
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, toggleLanguage, t: (key: TranslationKey) => copy[language][key] }), [language, setLanguage, toggleLanguage]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

// eslint-disable-next-line react-refresh/only-export-components
export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('useI18n must be used inside I18nProvider'); return value; }
