import { useState } from 'react';
import { ArrowLeft, Eye, EyeOff, LockKeyhole } from 'lucide-react';
import logo from '@/assets/branding/loktaal-logo.png';
import { AppLink, useRouter } from '@/contexts/RouterContext';
import { useI18n } from '@/contexts/I18nContext';
import { useAuth } from '@/contexts/AuthContext';
import { frontendOnlyAuthService } from '@/services/authService';
import { safeRedirect } from '@/lib/routing';

export function LoginPage() {
  const { t } = useI18n(); const { search, navigate } = useRouter(); const { enableAuthenticatedPreview } = useAuth();
  const [values, setValues] = useState({ email: '', password: '' }); const [show, setShow] = useState(false); const [error, setError] = useState('');
  const redirect = safeRedirect(search.get('redirect'), '/upload');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(values.email) || !values.password) { setError('Enter a valid email and password.'); return; } try { await frontendOnlyAuthService.signIn(values); } catch (reason) { setError(reason instanceof Error ? reason.message : t('auth.backendPending')); } };
  return <AuthLayout><form onSubmit={submit} noValidate className="rounded-3xl border border-white/15 bg-white/[.07] p-6 shadow-2xl backdrop-blur-xl sm:p-9"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#F0B23D]"><LockKeyhole className="h-4 w-4" />Frontend-only auth</p><h1 className="mt-4 font-devanagari text-3xl">{t('auth.login')}</h1><p className="mt-2 text-sm leading-6 text-white/60">{t('auth.previewNote')}</p>{error && <div role="alert" className="mt-5 rounded-xl border border-[#ff9e86]/30 bg-[#ff9e86]/10 p-3 text-sm text-[#ffc4b7]">{error}</div>}<div className="mt-6 space-y-4"><Field label={t('auth.email')} type="email" value={values.email} onChange={(value) => setValues({ ...values, email: value })} /><PasswordField label={t('auth.password')} value={values.password} show={show} setShow={setShow} onChange={(value) => setValues({ ...values, password: value })} showText={show ? t('auth.hide') : t('auth.show')} /></div><button type="submit" className="mt-6 min-h-12 w-full rounded-full border border-white/20 font-bold">{t('auth.login')}</button><button type="button" onClick={() => setError(t('auth.backendPending'))} className="mt-3 w-full text-sm text-[#D8C5EA] underline underline-offset-4">{t('auth.forgot')}</button><div className="my-6 h-px bg-white/10" /><button type="button" onClick={() => { enableAuthenticatedPreview(); navigate(redirect); }} className="min-h-12 w-full rounded-full bg-gradient-to-r from-[#E06543] to-[#F0B23D] px-5 font-bold text-[#25113f]">{t('auth.preview')}</button><p className="mt-6 text-center text-sm text-white/65">{t('auth.noAccount')} <AppLink to={`/signup?redirect=${encodeURIComponent(redirect)}`} className="font-bold text-[#F0B23D]">{t('auth.signup')}</AppLink></p></form></AuthLayout>;
}

export function SignupPage() {
  const { t } = useI18n(); const { search } = useRouter(); const [show, setShow] = useState(false); const [values, setValues] = useState({ fullName: '', email: '', password: '', confirm: '', terms: false }); const [error, setError] = useState('');
  const redirect = safeRedirect(search.get('redirect'), '/upload');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!values.fullName.trim() || !/^\S+@\S+\.\S+$/.test(values.email) || values.password.length < 8 || values.password !== values.confirm || !values.terms) { setError('Check every field, use at least 8 characters, and confirm the passwords match.'); return; } try { await frontendOnlyAuthService.signUp(values); } catch (reason) { setError(reason instanceof Error ? reason.message : t('auth.backendPending')); } };
  return <AuthLayout><form onSubmit={submit} noValidate className="rounded-3xl border border-white/15 bg-white/[.07] p-6 shadow-2xl backdrop-blur-xl sm:p-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#F0B23D]">Frontend-only auth</p><h1 className="mt-4 font-devanagari text-3xl">{t('auth.signup')}</h1><p className="mt-2 text-sm text-white/60">{t('auth.previewNote')}</p>{error && <div role="alert" className="mt-5 rounded-xl border border-[#ff9e86]/30 bg-[#ff9e86]/10 p-3 text-sm text-[#ffc4b7]">{error}</div>}<div className="mt-6 space-y-4"><Field label={t('auth.fullName')} value={values.fullName} onChange={(value) => setValues({ ...values, fullName: value })} /><Field label={t('auth.email')} type="email" value={values.email} onChange={(value) => setValues({ ...values, email: value })} /><PasswordField label={t('auth.password')} value={values.password} show={show} setShow={setShow} onChange={(value) => setValues({ ...values, password: value })} showText={show ? t('auth.hide') : t('auth.show')} /><Field label={t('auth.confirm')} type={show ? 'text' : 'password'} value={values.confirm} onChange={(value) => setValues({ ...values, confirm: value })} /><p className="text-xs text-white/55">Minimum 8 characters; use a mix of letters, numbers and symbols.</p><label className="flex gap-3 text-sm text-white/70"><input type="checkbox" checked={values.terms} onChange={(event) => setValues({ ...values, terms: event.target.checked })} className="mt-1 h-5 w-5 accent-[#F0B23D]" />{t('auth.terms')}</label></div><button type="submit" className="mt-6 min-h-12 w-full rounded-full bg-gradient-to-r from-[#E06543] to-[#F0B23D] font-bold text-[#25113f]">{t('auth.signup')}</button><p className="mt-6 text-center text-sm text-white/65">{t('auth.haveAccount')} <AppLink to={`/login?redirect=${encodeURIComponent(redirect)}`} className="font-bold text-[#F0B23D]">{t('auth.login')}</AppLink></p></form></AuthLayout>;
}

function AuthLayout({ children }: { children: React.ReactNode }) { const { t } = useI18n(); return <main data-theme="midnight-raga" className="min-h-screen bg-[radial-gradient(circle_at_80%_15%,rgba(147,51,234,.5),transparent_32%),linear-gradient(135deg,#25113f,#5B21B6_60%,#5B1F2A)] px-4 pb-16 pt-28 text-white sm:px-6"><div className="mx-auto max-w-lg"><AppLink to="/" className="mb-6 inline-flex min-h-11 items-center gap-2 text-sm text-white/65"><ArrowLeft className="h-4 w-4" />{t('common.backHome')}</AppLink><div className="mb-5 flex justify-center"><img src={logo} alt="Loktaal" className="w-44 rounded-xl bg-black/25 p-2" /></div>{children}</div></main>; }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 w-full rounded-xl border border-white/15 bg-white/5 px-4 outline-none focus:border-[#F0B23D]" /></label>; }
function PasswordField({ label, value, onChange, show, setShow, showText }: { label: string; value: string; onChange: (value: string) => void; show: boolean; setShow: (value: boolean) => void; showText: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><span className="flex min-h-12 items-center rounded-xl border border-white/15 bg-white/5 pr-2 focus-within:border-[#F0B23D]"><input required type={show ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 flex-1 bg-transparent px-4 outline-none" /><button type="button" onClick={() => setShow(!show)} aria-label={showText} className="flex h-10 w-10 items-center justify-center rounded-lg">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></span></label>; }
