import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, FileAudio, Image as ImageIcon, X } from 'lucide-react';
import { AppLink, useRouter } from '@/contexts/RouterContext';
import { useI18n } from '@/contexts/I18nContext';
import { useAuth } from '@/contexts/AuthContext';
import { indiaRegions } from '@/data/indiaStates';
import { createSongSubmission, updateSongSubmission, UploadCancelledError } from '@/services/songSubmissionService';
import { getMySubmission } from '@/services/songService';
import { friendlyBackendError } from '@/lib/submissionRules';
import type { UploadProgress } from '@/types/backend';
import type { SongRecord } from '@/types/backend';
import { formatFileSize, validateAudioFile, validateCoverFile, validateRequiredUploadFields } from '@/lib/uploadValidation';

const emptyForm = { contributorName: '', email: '', relationship: '', title: '', artist: '', stateSlug: '', district: '', language: '', tradition: '', instruments: '', year: '', description: '', culturalStory: '', lyrics: '', tags: '', consent: false, review: false };
type FormState = typeof emptyForm;

export function UploadPage() {
  const { t, language } = useI18n(); const { navigate, search } = useRouter(); const { isAuthenticated, loading, user, configured } = useAuth();
  const [values, setValues] = useState<FormState>(() => { try { return { ...emptyForm, ...JSON.parse(sessionStorage.getItem('loktaal-upload-draft') ?? '{}'), consent: false, review: false }; } catch { return emptyForm; } });
  const [audioFile, setAudioFile] = useState<File | null>(null); const [coverFile, setCoverFile] = useState<File | null>(null); const [fileErrors, setFileErrors] = useState({ audio: '', cover: '' }); const [errors, setErrors] = useState<Record<string, string>>({}); const [submitError, setSubmitError] = useState(''); const [submitting, setSubmitting] = useState(false); const [progress, setProgress] = useState<UploadProgress>({ stage: 'idle', audio: 0, cover: 0, overall: 0 }); const [existing, setExisting] = useState<SongRecord | null>(null); const [loadingDraft, setLoadingDraft] = useState(Boolean(search.get('edit'))); const abortRef = useRef<AbortController | null>(null);
  const audioInput = useRef<HTMLInputElement>(null); const coverInput = useRef<HTMLInputElement>(null);
  const audioUrl = useMemo(() => audioFile ? URL.createObjectURL(audioFile) : '', [audioFile]); const coverUrl = useMemo(() => coverFile ? URL.createObjectURL(coverFile) : '', [coverFile]);
  const dirty = Object.entries(values).some(([key, value]) => key !== 'consent' && key !== 'review' && Boolean(value)) || Boolean(audioFile || coverFile);
  useEffect(() => () => { if (audioUrl) URL.revokeObjectURL(audioUrl); }, [audioUrl]); useEffect(() => () => { if (coverUrl) URL.revokeObjectURL(coverUrl); }, [coverUrl]);
  useEffect(() => { const safeDraft = Object.fromEntries(Object.entries(values).filter(([key]) => key !== 'consent' && key !== 'review')); sessionStorage.setItem('loktaal-upload-draft', JSON.stringify(safeDraft)); }, [values]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty && !submitting) event.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty, submitting]);
  useEffect(() => { if (!loading && !isAuthenticated) navigate('/login?redirect=/upload', { replace: true }); }, [isAuthenticated, loading, navigate]);
  useEffect(() => { const songId = search.get('edit'); if (!songId || !user) { setLoadingDraft(false); return; } getMySubmission(songId, user.id).then((song) => { if (song.status !== 'draft' && song.status !== 'rejected') throw new Error('This submission can no longer be edited.'); setExisting(song); setValues({ contributorName: song.contributor_name, email: user.email ?? '', relationship: song.contributor_relationship, title: song.title, artist: song.artist_name, stateSlug: song.state_slug, district: song.district_region, language: song.language, tradition: song.folk_genre, instruments: song.instruments.join(', '), year: song.recording_year ? String(song.recording_year) : '', description: song.description, culturalStory: song.cultural_story, lyrics: song.lyrics ?? '', tags: song.tags.join(', '), consent: song.rights_confirmed, review: true }); }).catch((reason) => setSubmitError(friendlyBackendError(language, reason instanceof Error ? reason.message : undefined))).finally(() => setLoadingDraft(false)); }, [language, search, user]);
  useEffect(() => () => abortRef.current?.abort(), []);
  if (loading || loadingDraft || !isAuthenticated || !user) return <main className="min-h-screen bg-[#25113f] px-6 pt-36 text-center text-white">{language === 'hi' ? 'सुरक्षित सत्र जाँचा जा रहा है…' : 'Checking your secure session…'}</main>;

  const update = (key: keyof FormState, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  const selectAudio = (file?: File) => { if (!file) return; const error = validateAudioFile(file); setFileErrors((current) => ({ ...current, audio: error })); if (!error) setAudioFile(file); };
  const selectCover = (file?: File) => { if (!file) return; const error = validateCoverFile(file); setFileErrors((current) => ({ ...current, cover: error })); if (!error) setCoverFile(file); };
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); if (submitting) return;
    const nextErrors = validateRequiredUploadFields(values); if (!audioFile && !existing?.audio_path) nextErrors.audio = 'An MP3 or M4A audio file is required.'; setErrors(nextErrors); if (Object.keys(nextErrors).length || fileErrors.audio || fileErrors.cover || (!audioFile && !existing?.audio_path)) { document.getElementById('upload-errors')?.focus(); return; }
    setSubmitting(true); setSubmitError(''); const controller = new AbortController(); abortRef.current = controller;
    try { if (existing) await updateSongSubmission(existing, { metadata: values, ...(audioFile ? { audioFile } : {}), ...(coverFile ? { coverFile } : {}) }, user.id, setProgress, controller.signal); else if (audioFile) await createSongSubmission({ metadata: values, audioFile, ...(coverFile ? { coverFile } : {}) }, user.id, setProgress, controller.signal); sessionStorage.removeItem('loktaal-upload-draft'); navigate('/my-submissions?submitted=1', { replace: true }); }
    catch (reason) { setSubmitError(reason instanceof UploadCancelledError ? (language === 'hi' ? 'अपलोड रद्द हुआ। आपकी फ़ाइलें सहेजी नहीं गईं।' : 'Upload cancelled. Your files were not saved.') : friendlyBackendError(language, reason instanceof Error ? reason.message : undefined)); }
    finally { setSubmitting(false); abortRef.current = null; }
  };

  return <main data-theme="archive-paper" className="min-h-screen bg-[var(--page-bg)] px-4 pb-24 pt-28 text-[var(--text-primary)] sm:px-6"><div className="mx-auto max-w-5xl"><AppLink to={existing ? '/my-submissions' : '/'} className="inline-flex min-h-11 items-center gap-2 text-sm text-[var(--text-secondary)]"><ArrowLeft className="h-4 w-4" />{existing ? (language === 'hi' ? 'मेरे सबमिशन' : 'My submissions') : t('common.backHome')}</AppLink><header className="mt-8"><p className="text-xs font-bold uppercase tracking-[.24em] text-[var(--accent-primary)]">Secure contributor flow</p><h1 className="mt-4 font-devanagari text-4xl sm:text-6xl">{existing ? (language === 'hi' ? 'सबमिशन संपादित करें' : 'Edit submission') : t('upload.title')}</h1><p className="mt-3 text-[var(--text-secondary)]">{t('upload.intro')}</p></header>
    <form onSubmit={submit} noValidate className="mt-10 space-y-6"><div id="upload-errors" tabIndex={-1} aria-live="polite">{(Object.keys(errors).length > 0 || submitError) && <div role="alert" className="rounded-2xl border border-[#9E302D]/25 bg-[#9E302D]/10 p-4 text-sm text-[#7b211f]">{submitError || (language === 'hi' ? 'आगे बढ़ने से पहले आवश्यक फ़ील्ड जाँचें।' : 'Please review the highlighted required fields before continuing.')}</div>}</div>
      <FormSection title={t('upload.contributor')} number="01"><div className="grid gap-4 md:grid-cols-2"><TextField label={t('upload.contributorName')} required value={values.contributorName} onChange={(value) => update('contributorName', value)} error={errors.contributorName} /><TextField label={t('auth.email')} type="email" required value={values.email} onChange={(value) => update('email', value)} error={errors.email} /><SelectField label={t('upload.relationship')} required value={values.relationship} onChange={(value) => update('relationship', value)} error={errors.relationship} options={['Artist/performer', 'Collector/researcher', 'Rights holder', 'Other']} /></div></FormSection>
      <FormSection title={t('upload.song')} number="02"><div className="grid gap-4 md:grid-cols-2"><TextField label={t('upload.songTitle')} required value={values.title} onChange={(value) => update('title', value)} error={errors.title} /><TextField label={t('upload.artist')} required value={values.artist} onChange={(value) => update('artist', value)} error={errors.artist} /><SelectField label={t('upload.state')} required value={values.stateSlug} onChange={(value) => update('stateSlug', value)} error={errors.stateSlug} options={indiaRegions.map((region) => ({ value: region.slug, label: language === 'hi' ? `${region.nameHi} · ${region.name}` : `${region.name} · ${region.nameHi}` }))} /><TextField label={t('upload.district')} required value={values.district} onChange={(value) => update('district', value)} error={errors.district} /><TextField label={t('upload.language')} required value={values.language} onChange={(value) => update('language', value)} error={errors.language} /><TextField label={t('upload.tradition')} required value={values.tradition} onChange={(value) => update('tradition', value)} error={errors.tradition} /><TextField label={t('upload.instruments')} value={values.instruments} onChange={(value) => update('instruments', value)} /><TextField label={t('upload.year')} type="number" value={values.year} onChange={(value) => update('year', value)} /></div><div className="mt-4 space-y-4"><TextArea label={t('upload.description')} required value={values.description} onChange={(value) => update('description', value)} error={errors.description} /><TextArea label={t('upload.context')} required value={values.culturalStory} onChange={(value) => update('culturalStory', value)} error={errors.culturalStory} /><TextArea label={t('upload.lyrics')} value={values.lyrics} onChange={(value) => update('lyrics', value)} /><TextField label={t('upload.tags')} value={values.tags} onChange={(value) => update('tags', value)} /></div></FormSection>
      <FormSection title={t('upload.files')} number="03">{existing?.audio_path && !audioFile && <p className="mb-4 rounded-xl bg-[var(--border-subtle)] p-3 text-sm">{language === 'hi' ? 'मौजूदा ऑडियो रखा जाएगा; बदलने के लिए नई फ़ाइल चुनें।' : 'The existing audio will be kept; choose a new file only to replace it.'}</p>}<div className="grid gap-5 md:grid-cols-2"><FileBox icon={<FileAudio />} title={t('upload.audio')} detail="Maximum 25 MB" error={fileErrors.audio || errors.audio} file={audioFile} inputRef={audioInput} accept=".mp3,.m4a,audio/mpeg,audio/mp4,audio/x-m4a" onSelect={selectAudio} onRemove={() => { setAudioFile(null); if (audioInput.current) audioInput.current.value = ''; }} /> <FileBox icon={<ImageIcon />} title={t('upload.cover')} detail="Maximum 3 MB" error={fileErrors.cover} file={coverFile} inputRef={coverInput} accept="image/jpeg,image/png,image/webp" onSelect={selectCover} onRemove={() => { setCoverFile(null); if (coverInput.current) coverInput.current.value = ''; }} /></div>{audioUrl && <div className="mt-5 rounded-2xl border border-[var(--border-subtle)] p-4"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[var(--accent-primary)]">Temporary browser preview</p><audio controls src={audioUrl} className="w-full">Your browser cannot preview this audio.</audio></div>}{coverUrl && <div className="mt-5"><img src={coverUrl} alt="Selected cover preview" className="h-52 w-full rounded-2xl object-cover" /></div>}</FormSection>
      <FormSection title={t('upload.rights')} number="04"><Checkbox checked={values.consent} onChange={(value) => update('consent', value)} label={t('upload.consent')} error={errors.consent} /><Checkbox checked={values.review} onChange={(value) => update('review', value)} label={t('upload.review')} error={errors.review} /></FormSection>
      <div className="flex flex-col items-start justify-between gap-4 rounded-3xl bg-[#25113f] p-6 text-white sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-bold">{language === 'hi' ? 'निजी और सुरक्षित अपलोड' : 'Private, secure upload'}</p><p className="mt-1 text-sm text-white/60">{configured ? (language === 'hi' ? 'फ़ाइलें निजी संग्रह में जाएँगी और समीक्षा के बाद ही सार्वजनिक होंगी।' : 'Files stay private and become public only after approval.') : (language === 'hi' ? 'Supabase कॉन्फ़िगरेशन उपलब्ध नहीं है।' : 'Supabase configuration is unavailable.')}</p>{submitting && <div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-[#F0B23D] transition-all" style={{ width: `${progress.overall}%` }} /></div><p className="mt-2 text-xs text-white/65">{progress.stage} · {progress.overall}%</p></div>}</div><div className="flex gap-2">{submitting && <button type="button" onClick={() => abortRef.current?.abort()} className="min-h-12 rounded-full border border-white/30 px-5 font-bold">{language === 'hi' ? 'रद्द करें' : 'Cancel'}</button>}<button type="submit" disabled={submitting || !configured} className="min-h-12 rounded-full bg-[#F0B23D] px-6 font-bold text-[#25113f] disabled:opacity-50">{submitting ? (language === 'hi' ? 'अपलोड हो रहा है…' : 'Uploading…') : (language === 'hi' ? 'समीक्षा के लिए भेजें' : 'Submit for review')}</button></div></div>
    </form></div></main>;
}

function FormSection({ title, number, children }: { title: string; number: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-[var(--border-subtle)] bg-[var(--surface)] p-5 sm:p-8"><div className="mb-6 flex items-center gap-3"><span className="font-display text-xl font-bold text-[var(--accent-primary)]">{number}</span><h2 className="font-devanagari text-2xl">{title}</h2></div>{children}</section>; }
function TextField({ label, value, onChange, type = 'text', required, error }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; error?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}{required && <span className="text-[var(--accent-primary)]"> *</span>}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(error)} className="min-h-12 w-full rounded-xl border border-[var(--border-subtle)] bg-white/45 px-4 outline-none focus:border-[var(--accent-primary)]" />{error && <span className="mt-1 block text-xs text-[#9E302D]">{error}</span>}</label>; }
function TextArea({ label, value, onChange, required, error }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; error?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}{required && <span className="text-[var(--accent-primary)]"> *</span>}</span><textarea rows={4} value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(error)} className="w-full rounded-xl border border-[var(--border-subtle)] bg-white/45 p-4 outline-none focus:border-[var(--accent-primary)]" />{error && <span className="mt-1 block text-xs text-[#9E302D]">{error}</span>}</label>; }
function SelectField({ label, value, onChange, options, required, error }: { label: string; value: string; onChange: (value: string) => void; options: Array<string | { value: string; label: string }>; required?: boolean; error?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}{required && <span className="text-[var(--accent-primary)]"> *</span>}</span><select value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(error)} className="min-h-12 w-full rounded-xl border border-[var(--border-subtle)] bg-white/45 px-4 outline-none"><option value="">Select…</option>{options.map((option) => { const item = typeof option === 'string' ? { value: option, label: option } : option; return <option key={item.value} value={item.value}>{item.label}</option>; })}</select>{error && <span className="mt-1 block text-xs text-[#9E302D]">{error}</span>}</label>; }
function Checkbox({ checked, onChange, label, error }: { checked: boolean; onChange: (value: boolean) => void; label: string; error?: string }) { return <label className="mb-4 flex gap-3 rounded-2xl border border-[var(--border-subtle)] p-4"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-[var(--accent-primary)]" /><span className="text-sm leading-6">{label}{error && <span className="mt-1 block text-xs text-[#9E302D]">{error}</span>}</span></label>; }
function FileBox({ icon, title, detail, error, file, inputRef, accept, onSelect, onRemove }: { icon: React.ReactNode; title: string; detail: string; error?: string; file: File | null; inputRef: React.RefObject<HTMLInputElement>; accept: string; onSelect: (file?: File) => void; onRemove: () => void }) { return <div className="rounded-2xl border border-dashed border-[var(--border-subtle)] p-5"><div className="flex items-center gap-3 text-[var(--accent-primary)]">{icon}<p className="font-bold text-[var(--text-primary)]">{title}</p></div><p className="mt-1 text-xs text-[var(--text-secondary)]">{detail}</p><input ref={inputRef} type="file" accept={accept} onChange={(event) => onSelect(event.target.files?.[0])} className="mt-4 block w-full text-sm file:mr-3 file:min-h-11 file:rounded-full file:border-0 file:bg-[var(--accent-primary)] file:px-4 file:font-bold file:text-white" />{file && <div className="mt-4 flex items-center justify-between gap-3 rounded-xl bg-[var(--border-subtle)] p-3"><span className="min-w-0 text-xs"><span className="block truncate font-semibold">{file.name}</span><span>{formatFileSize(file.size)}</span></span><button type="button" onClick={onRemove} aria-label={`Remove ${file.name}`} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full"><X className="h-4 w-4" /></button></div>}{error && <p className="mt-2 text-xs text-[#9E302D]">{error}</p>}</div>; }
